### PR TITLE
Improvements for sysconfig.spec

### PR DESCRIPTION
**Pull request by Vogtinator**
Mainly drop the hard and soft dependency on wicked.

### CODE REVIEW

**Review by mtomaschewski — APPROVED** [review]

**Comment by Vogtinator** [comment]
Can you please submit this?

**Comment by mtomaschewski** [comment]
Yes, I'll do it today. Sorry for the delay!

**Comment by mtomaschewski** [comment]
BTW: Do we need  the `Suggests:       wicked-service`  at all?

**Comment by Vogtinator** [comment]
I'm not entirely sure, but I can't find anything else which pulls in wicked. Which means that if you install `pattern-base` (or `sysconfig-netconfig`), `zypper` would select `NetworkManager` instead due to alphabetical sorting.

**Comment by mtomaschewski** [comment]
Effectively, it depends on the product pattern in yast2 installer [¹] which one yast2 proposes by default. That is, IMO we don't even need a suggestion. Wicked requires sysconfig (/etc/sysconfig/network/config,dhcp) + sysconfig-netconfig, but not the another way around. The recommends was there to provide/enable a SLES-11 /sbin/ifup compatibility by default.

So I'd say, let's remove the suggestion too -- also other installers than yast2 need to decide what they prefer. Objections?

[¹] @teclator do you know more about?

**Comment by Vogtinator** [comment]
No objection from me! IMO suggestions like this belong into pattern or release packages anyway.

**Comment by DimStar77** [comment]
> Effectively **AFAIK**, it depends on the product pattern in yast2 installer [¹] which one yast2 proposes by default. That is, IMO we don't even need a suggestion. Wicked requires sysconfig (/etc/sysconfig/network/config,dhcp) + sysconfig-netconfig, but not the another way around. The recommends was there to provide/enable a SLES-11 /sbin/ifup compatibility by default.

Not everything is always installed using yast from a fresh install. Think containers, or even upgrades from older distros where things might change.

The Suggests: has no impact other than for zypper to know 'if something asks me for service(network) and I have a a choice, I will favor wicked-service'

At this moment, the thing is mostly moot, as sysconfig requires /sbin/ifup - which is exclusively provided by wicked-service (which is otoh quite confusing for NetworkManager-based installs) - so essentially at this moment wicker-service is a hard requires anyway

**Comment by DimStar77** [comment]
```
	sysconfig is needed by (installed) patterns-base-base-20200505-17.1.x86_64
	sysconfig is needed by (installed) firewalld-0.9.3-3.3.noarch
…
	/sbin/ifup is needed by (installed) sysconfig-0.85.6-2.4.x86_64
```

**Comment by Vogtinator** [comment]
@DimStar77 This PR dropped the hard requirement, so the suggests is relevant now.

**Comment by mtomaschewski** [comment]
> [...] The Suggests: has no impact other than for zypper to know 'if something asks me for service(network) and I have a a choice, I will favor wicked-service'

OK, than taking with the suggests as it is.

**Comment by mtomaschewski** [comment]
> Can you please submit this?
https://build.opensuse.org/request/show/898471

**Pull request merged**
