### PR TITLE
netconfig: only write files on a change (bsc#1176325)

### PR DESCRIPTION
**Pull request by mtomaschewski**
Avoid e.g. dnsmasq (if running) to re-read /etc/resolv.conf and re-initialize itself without a content change.

### CODE REVIEW

**Review by rma-x — COMMENTED** [review]
The nested chains of ||s and &&s seem to be correct, but I find them hard to read and understand. There is some room for simplification e.g. by removing one && and starting the cmp command on a new line. Also, given how similar the six incarnations of this code block are, maybe it could be generalized and factored out to functions.netconfig.

**Comment by mtomaschewski** [comment]
Yes, this probably makes sense.

**Comment by mtomaschewski** [comment]
What's not needed is:
```
-    } && cmp -s -- "$TMP_FILE" "$ROOT$DESTFILE" && {
+    }
+    cmp -s -- "$TMP_FILE" "$ROOT$DESTFILE"      && {
```
so it would be effectively:
```
    dump_named_forwarders "$@" >> "$TMP_FILE"   || {
        rm -f -- "$TMP_FILE" ; return 3
    }
    cmp -s -- "$TMP_FILE" "$ROOT$DESTFILE"      && {
        rm -f -- "$TMP_FILE" # unchanged
    } || {
        mv -f -- "$TMP_FILE" "$ROOT$DESTFILE"   || {
            rm -f -- "$TMP_FILE" ; return 3
        }
        changed=1
    }
    debug "dns settings written to $DESTFILE"
```

Instead of  ||s and &&s it'd be possible to use if and else:
```
    if ! dump_named_forwarders "$@" >> "$TMP_FILE" ; then
        rm -f -- "$TMP_FILE" ; return 3
    fi
    if cmp -s -- "$TMP_FILE" "$ROOT$DESTFILE"    ; then
        rm -f -- "$TMP_FILE" # unchanged
    elif mv -f -- "$TMP_FILE" "$ROOT$DESTFILE"   ; then
        changed=1
    else
        rm -f -- "$TMP_FILE" ; return 3
    fi
```
Going to change to the above as next incarnation.

The cmp + mv could  be moved to functions.netconfig as e.g.:
```
netconfig_move_to_dest()
{
    local temp_file="$1"
    local dest_file="$2"

    test "X$dest_file" = X && return 3
    test "X$temp_file" = X && return 3
    test -f "$temp_file"   || return 3

    cmp -s -- "$temp_file" "$dest_file" && return 1
    mv -f -- "$temp_file" "$dest_file"  || return 3
    return 0 # changed
}
```
or with -a instead:
```
    test "X$temp_file" != X -a -f "$temp_file" -a \
         "X$dest_file" != X             || return 3
```
but it doesn't make the code shorter, as it requires to handle 0 (changed), 1 (unchanged), 3 (failure)
later... better ideas?

**Comment by rma-x** [comment]
You could also move creation and removal of the temporary file down into `netconfig_move_to_dest`.
For creation either pipe the output of the content creator into the function or pass its name as an argument. For removal you could add a `trap "..." RETURN` to the function.

**Comment by mtomaschewski** [comment]
yes, a trap would be a way. tomorrow.

**Comment by mtomaschewski** [comment]
No, I didn't found a way that reduces the complexity. Whatever we do, we need to handle 0 (changed), 1 (unchanged), 3 (failure) results and by moving the (dump +) cmp + mv to a function. The difference is just that we're using the result codes
in `if elif else` instead of (`dump`) + `if cmp elif mv else` that we're using now plus a quite complex code inside the function.

Thus, I'd stay with the current variant -- it's not worth to spend further time with it IMO.

**Pull request merged**
