### PR TITLE
Moved installs scripts to a FHS conform place

### PR DESCRIPTION
**Pull request by schubi2**
Moved:
/etc/sysconfig/network/scripts -> /usr/libexec/netconfig/scripts
/etc/netconfig.d  -> /usr/libexec/netconfig/netconfig.d/

This is the implementation of:
https://github.com/openSUSE/sysconfig/issues/33

### CODE REVIEW

**Review by mtomaschewski — CHANGES_REQUESTED** [review]
See https://github.com/openSUSE/sysconfig/pull/36#issuecomment-1056814751

**Comment by mtomaschewski** [comment]
BTW: I know at least 3 SLES customers installing modules in /etc/netconfig.d/, e.g. to process custom dhcp options - that is it's also mandatory consider/cover this...

**Comment by schubi2** [comment]
> These changes are **P1** regression bug candidates and definitely nothing for an 0.85.9 update, but rather for 0.86.0 after SLE-15-SP4 release, thus please remove the changes to VERSION and `- version 0.85.9` from package changes.
> 
> There is no /usr/libexec on 64bit platforms (see `rpm -E '%_libexecdir'` on e.g. x86_64), what says to me that these changes are also untested.

They are tested with TW. OK, ping me again (after SP4) if it fits to your planing.

**Comment by thkukuk** [comment]
> There is no /usr/libexec on 64bit platforms (see `rpm -E '%_libexecdir'` on e.g. x86_64), what says to me that these
> changes are also untested.
rpm -E '%_libexecdir'
/usr/libexec

This change is now 2 years old. And it's time to adjust your packages in Tumbleweed for the successor of SLES following the current rules.

**Pull request closed without merging**
